import { MAP_FWD as ITU_FWD } from './mapping_itu';

export const MAP_FWD: Record<string, string> = {
  // Letters
  'А': '.-',
  'Б': '-...',
  'В': '.--',
  'Г': '--.',
  'Д': '-..',
  'Е': '.',
  'Ж': '...-',
  'З': '--..',
  'И': '..',
  'Й': '.---',
  'К': '-.-',
  'Л': '.-..',
  'М': '--',
  'Н': '-.',
  'О': '---',
  'П': '.--.',
  'Р': '.-.',
  'С': '...',
  'Т': '-',
  'У': '..-',
  'Ф': '..-.',
  'Х': '....',
  'Ц': '-.-.',
  'Ч': '---.',
  'Ш': '----',
  'Щ': '--.-',
  'Ы': '-.--',
  'Ь': '-..-',
  'Э': '..-..',
  'Ю': '..--',
  'Я': '.-.-',
  // Digits and punctuation (reuse ITU)
  '0': ITU_FWD['0'],
  '1': ITU_FWD['1'],
  '2': ITU_FWD['2'],
  '3': ITU_FWD['3'],
  '4': ITU_FWD['4'],
  '5': ITU_FWD['5'],
  '6': ITU_FWD['6'],
  '7': ITU_FWD['7'],
  '8': ITU_FWD['8'],
  '9': ITU_FWD['9'],
  '.': ITU_FWD['.'],
  ',': ITU_FWD[','],
  '?': ITU_FWD['?'],
  "'": ITU_FWD["'"],
  '!': ITU_FWD['!'],
  '/': ITU_FWD['/'],
  '(': ITU_FWD['('],
  ')': ITU_FWD[')'],
  '&': ITU_FWD['&'],
  ':': ITU_FWD[':'],
  ';': ITU_FWD[';'],
  '=': ITU_FWD['='],
  '+': ITU_FWD['+'],
  '-': ITU_FWD['-'],
  '_': ITU_FWD['_'],
  '"': ITU_FWD['"'],
  '$': ITU_FWD['$'],
  '@': ITU_FWD['@']
};

export const MAP_REV: Record<string, string> = Object.fromEntries(
  Object.entries(MAP_FWD).map(([char, code]) => [code, char])
) as Record<string, string>;
